#!/bin/sh
#
# Re-used example from SJD
#

set -e

stamp="$COSMOS_BASE/stamps/puppet-tools-v01.stamp"

if ! test -f $stamp -a -f /usr/bin/puppet; then
    apt-get update
    apt-get -y install puppet

    mkdir -p `dirname $stamp`
    touch $stamp
fi
