#!/bin/sh

if [ "x$COSMOS_VERBOSE" = "xy" ]; then
   args="--verbose"
else
   args="--logdest=syslog"
fi

if [ -f /usr/bin/puppet -a -d /etc/puppet/manifests ]; then
   for m in `find /etc/puppet/manifests -name \*.pp`; do
      puppet apply $args $m
   done
fi
